"""empty message

Revision ID: 1ac928c61875
Revises: d86319b46a8b
Create Date: 2024-07-31 03:32:29.063535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac928c61875'
down_revision: Union[str, None] = 'd86319b46a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proofShot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('photoComment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userProofShot',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['proofShot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'photo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userProofShot')
    op.drop_table('proofShot')
    # ### end Alembic commands ###