"""empty message

Revision ID: 844f47f036f7
Revises: d8ce654f2ebb
Create Date: 2024-08-02 19:14:48.048953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844f47f036f7'
down_revision: Union[str, None] = 'd8ce654f2ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolist', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todolist', 'userinfo', ['user_id'], ['id'])
    op.add_column('userinfo', sa.Column('age_group', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userinfo', 'age_group')
    op.drop_constraint(None, 'todolist', type_='foreignkey')
    op.drop_column('todolist', 'user_id')
    # ### end Alembic commands ###
