"""Add userdiary tables

Revision ID: 9f8ac35f81a3
Revises: d8ce654f2ebb
Create Date: 2024-08-03 14:37:40.519769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8ac35f81a3'
down_revision: Union[str, None] = 'd8ce654f2ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdiary', sa.Column('Diaryuserid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdiary', 'Diaryuserid')
    # ### end Alembic commands ###
