"""empty message

Revision ID: d86319b46a8b
Revises: e8fb0e7ed15b
Create Date: 2024-07-29 23:17:18.201084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd86319b46a8b'
down_revision: Union[str, None] = 'e8fb0e7ed15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challengeOwner', sa.String(), nullable=False),
    sa.Column('challengeTitle', sa.String(), nullable=False),
    sa.Column('challengeComment', sa.Text(), nullable=False),
    sa.Column('challenger', sa.Integer(), nullable=False),
    sa.Column('challengeReward', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('challengeThumbnail1', sa.String(), nullable=False),
    sa.Column('challengeThumbnail2', sa.String(), nullable=True),
    sa.Column('challengeThumbnail3', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userChallenge',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'challenge_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userChallenge')
    op.drop_table('challenge')
    # ### end Alembic commands ###
