"""empty message

Revision ID: 138cd61d8975
Revises: f53fb7131e3f
Create Date: 2024-07-21 22:05:12.201854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '138cd61d8975'
down_revision: Union[str, None] = 'f53fb7131e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('todo', sa.String(), nullable=False),
    sa.Column('check', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todolist_id'), 'todolist', ['id'], unique=False)
    op.create_table('userdiary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=False),
    sa.Column('Diarycontent', sa.Text(), nullable=False),
    sa.Column('Response', sa.Text(), nullable=False),
    sa.Column('Diarytodo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.String(), nullable=False),
    sa.Column('userPassword', sa.String(), nullable=False),
    sa.Column('userName', sa.String(), nullable=False),
    sa.Column('userBirth', sa.Date(), nullable=False),
    sa.Column('userEmail', sa.String(), nullable=False),
    sa.Column('userGender', sa.Integer(), nullable=False),
    sa.Column('userPpojakCoin', sa.Integer(), nullable=False),
    sa.Column('userProfileName', sa.String(), nullable=False),
    sa.Column('userProfileComment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userinfo')
    op.drop_table('userdiary')
    op.drop_index(op.f('ix_todolist_id'), table_name='todolist')
    op.drop_table('todolist')
    # ### end Alembic commands ###
